-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isNewUser" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "completedTours" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
